version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: usersdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

#volumes:
#  mysql_data: