apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      containers:
        - name: api
          image: egormayer/devsecops-api
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
            - name: DB_NAME
              value: users-db
          ports:
            - containerPort: 8000
