apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      containers:
        - name: devsecops
          image: monokkay/devsecops-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: secretPassword
            - name: DB_NAME
              value: users_db
