apiVersion: v1
kind: configMap
metadata:
  name: devsecops-config
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: monokkai
  APP_MODE: production
  LOG_LEVEL: info

---

apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secret
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0UGFzc3dvcmQ=